# Generated by Django 3.2.23 on 2025-12-10 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='check_in_method',
            field=models.CharField(choices=[('MANUAL', 'Thủ công'), ('FACE', 'Nhận diện khuôn mặt')], default='MANUAL', max_length=10),
        ),
        migrations.AddField(
            model_name='attendance',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_attendances', to='main.staffinfo'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_status',
            field=models.IntegerField(choices=[(1, 'Vắng'), (2, 'Có mặt'), (3, 'Muộn')]),
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id_session', models.BigAutoField(primary_key=True, serialize=False)),
                ('session_date', models.DateField()),
                ('session_number', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Chưa bắt đầu'), ('OPEN', 'Đang điểm danh'), ('CLOSED', 'Đã kết thúc')], default='PENDING', max_length=20)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('id_classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='main.classroom')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_sessions', to='main.staffinfo')),
            ],
            options={
                'ordering': ['-session_date', '-session_number'],
                'unique_together': {('id_classroom', 'session_date')},
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='id_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='main.classsession'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('id_session', 'id_student')},
        ),
    ]
